name: get-posts-akuko-lambda-depl

on:
  push:
    branches:
      - master
    paths:
      - "lambdas/get-posts-akuko/**"
jobs:
  deploy_source:
    name: build and deploy get-posts-akuko-lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip folder contents
        run: cd lambdas && zip -qq -r -j ./get-posts-akuko-bundle.zip ./get-posts-akuko/*
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: get-posts-akuko
          zip_file: lambdas/get-posts-akuko-bundle.zip
