name: posts-sentiment-analysis-lambda-depl

on:
  push:
    branches:
      - master
    paths:
      - "lambdas/posts-sentiment-analysis/**"
jobs:
  deploy_source:
    name: build and deploy posts-sentiment-analysis-lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip folder contents
        run: cd lambdas && zip -qq -r -j ./posts-sentiment-analysis-bundle.zip ./posts-sentiment-analysis/*
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: posts-sentiment-analysis
          zip_file: lambdas/posts-sentiment-analysis-bundle.zip
